apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
      - name: prometheus-config-volume
        hostPath:
          path: /c/Users/zhanxies/projects/prometheus/prometheus1.yml
      containers:
      - name: prometheus-container
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/prometheus.yml
        imagePullPolicy: IfNotPresent
        image: prom/prometheus:latest   